server:
  port: 8088
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service # 应用名称
  datasource:
    url: jdbc:mysql://localhost:3306/pcms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  druid:
    initial-size: 2
    min-idle: 2
    max-active: 20
    test-on-borrow: true
    stat-view-servlet:
      allow: true
  #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8001/eureka
      registry-fetch-interval-seconds: 60 # 获取服务列表
#  instance:
#    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
#    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
#    lease-expiration-duration-in-seconds: 90 # 服务失效时间，默认值90秒
#    lease-renewal-interval-in-seconds: 30 # 服务续约(renew )的间隔，默认为30秒

token:
  expire:
    seconds: 7200
  jwtSecret: infinova
  shortTime : 60

mybatis:
  mapper-locations: classpath*:mybatis-mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.infinova.authenticationservice.entity